allowBuilds:
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  handlebars: "^4.7.9"
  form-data: "^4.0.4"
  flatted: "^3.4.2"
  rollup: "^4.59.0"
